// Shared types for the oracle-world simulation layer.
// These flow between the worker, the WorldCanvas renderer, and the React page.

// Legacy 3-AI semantic factions (mapped to WorldBox races in the worker)
export type FactionType = 'believer' | 'apostate' | 'wanderer';
export type BehaviorState = 'idle' | 'migrate' | 'build' | 'flee' | 'attack';

// Numeric race IDs (used by the worker for compact storage)
export const RACE = {
  HUMAN: 1,
  ORC: 2,
  ELF: 3,
  LAND_FAUNA: 4,
  WATER_FAUNA: 5,
} as const;
export type RaceId = (typeof RACE)[keyof typeof RACE];

// Semantic → race mapping (Believer→Human, Apostate→Orc, Wanderer→Elf)
export const FACTION_TO_RACE: Record<FactionType, RaceId> = {
  believer: RACE.HUMAN,
  apostate: RACE.ORC,
  wanderer: RACE.ELF,
};
export const RACE_TO_FACTION: Record<RaceId, FactionType> = {
  [RACE.HUMAN]: 'believer',
  [RACE.ORC]: 'apostate',
  [RACE.ELF]: 'wanderer',
  [RACE.LAND_FAUNA]: 'wanderer',
  [RACE.WATER_FAUNA]: 'wanderer',
};

// EntityType encoding: race*10 + subtype (matches WorldBox spec)
// e.g. 10-19 humans (villager, knight, archer, mage, king, queen, ninja, priest, farmer, general)
//      20-29 orcs   30-39 elves   40-49 land fauna   50-59 water fauna
export type EntityTypeId = number;

// Action state for renderer animations
export const ACTION = {
  IDLE: 0,
  WALK: 1,
  ATTACK: 2,
  FLEE: 3,
  BUILD: 4,
} as const;
export type ActionId = (typeof ACTION)[keyof typeof ACTION];

// Biome IDs (must match mapGen output)
export const BIOME = {
  DEEP_SEA: 0,
  SHALLOW_SEA: 1,
  SAND: 2,
  GRASS: 3,
  FOREST: 4,
  MOUNTAIN: 5,
  SNOW: 6,
} as const;
export type BiomeId = (typeof BIOME)[keyof typeof BIOME];

// Display structures (mostly for HUD compatibility with existing components)
export interface SimBuilding {
  type: 'hut' | 'house' | 'tower' | 'keep' | 'temple' | 'shrine' | 'obelisk';
  x: number;
  y: number;
}

export interface SimRegion {
  id: number;
  x: number;
  y: number;
  population: number;
  faith: number;
  resources: number;
  faction: FactionType;
  isActive: boolean;
  foundedAt: number;
  level: number;
  buildings: SimBuilding[];
}

export interface SimEntity {
  id: number;
  regionId: number;
  type: FactionType;
  faith: number;
  karma: number;
  health: number;
  x: number;
  y: number;
  behavior: BehaviorState;
  direction: 'up' | 'down' | 'left' | 'right';
  isMoving: boolean;
}

export interface SimDivineEvent {
  toolId: number;
  toolName: string;
  polarity: 'good' | 'evil';
  description: string;
  targetRegionId: number;
  timestamp: number;
}

export interface SimWorldState {
  day: number;
  seed: string;
  regions: SimRegion[];
  entities: SimEntity[];
  totalPopulation: number;
  totalFaith: number;
  dominantFaction: FactionType | 'balanced';
  activeRegionsCount: number;
  lastUpdatedAt: number;
}

export interface WorkerUpdateMessage {
  type: 'TICK_UPDATE';
  state: SimWorldState;
  events: string[];
}

// ----- Render frame payload (zero-copy buffers from worker) -----
// The renderer reads these directly each frame; never serialized to JSON.

export interface RenderFrame {
  positions: Float32Array;   // [x0,y0, x1,y1, ...]
  velocities: Float32Array;  // for sprite flip direction
  types: Uint8Array;         // EntityTypeId per entity
  states: Uint8Array;        // ActionId per entity
  count: number;

  bPositions: Float32Array;
  bRaces: Uint8Array;
  bSubTypes: Uint8Array;     // 0-19 picks one of the 20 buildings per race
  bAges: Uint16Array;        // for grow-from-ground animation
  bCount: number;
}

// ----- Atlas manifest (generated by build-atlas.mjs) -----
export interface AtlasFrame {
  atlas: string;
  x: number;
  y: number;
  w: number;
  h: number;
}
export interface AtlasManifest {
  generated: string;
  spriteSize: number;
  tileSize: number;
  atlases: Record<string, { file: string; width: number; height: number }>;
  frames: Record<string, AtlasFrame>;
}

// ----- Tunables -----
export const WORLD_TILES = 1024;
export const TILE_PX = 16;
export const WORLD_PX = WORLD_TILES * TILE_PX;       // 16384 px continent
export const MAX_ENTITIES = 15000;
export const MAX_BUILDINGS = 5000;
export const SPATIAL_GRID_CELLS = 256;                // 256x256 grid cells
export const SPATIAL_CELL_PX = WORLD_PX / SPATIAL_GRID_CELLS; // 64 px per cell
